/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ifcopenshell_IfcOpenShellModel */

#ifndef _Included_org_ifcopenshell_IfcOpenShellModel
#define _Included_org_ifcopenshell_IfcOpenShellModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ifcopenshell_IfcOpenShellModel
 * Method:    getGeometry
 * Signature: ()Lorg/ifcopenshell/IfcGeomObject;
 */
JNIEXPORT jobject JNICALL Java_org_ifcopenshell_IfcOpenShellModel_getGeometry
  (JNIEnv *, jobject);

/*
 * Class:     org_ifcopenshell_IfcOpenShellModel
 * Method:    setIfcData
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ifcopenshell_IfcOpenShellModel_setIfcData
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_ifcopenshell_IfcOpenShellModel
 * Method:    getPluginVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_ifcopenshell_IfcOpenShellModel_getPluginVersion
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
