[build-system]
requires = ["setuptools>=77.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ifcclash"
version = "0.0.0"
authors = [
  { name="Dion Moult", email="dion@thinkmoult.com" },
]
description = "IFC clash detection library to handle intersections, collisions, and clearance checks"
readme = "README.md"
requires-python = ">=3.11"
license = "LGPL-3.0-or-later"
keywords = ["IFC", "clash", "BIM"]
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "ifcopenshell",
]

[project.optional-dependencies]
advanced = [
  "scikit-learn",
]

[project.urls]
Homepage = "http://ifcopenshell.org"
Documentation = "https://docs.ifcopenshell.org"
Issues = "https://github.com/IfcOpenShell/IfcOpenShell/issues"

[tool.setuptools.packages.find]
include = ["ifcclash"]
exclude = ["test*"]
