import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Literal, TypeAlias

import ifcopenshell


@dataclass
class FailObj:
    expected_count: int = 1


PassResult: TypeAlias = Literal["pass"]

Result = FailObj | PassResult


def normalize_header(f: ifcopenshell.file) -> None:
    f.header.file_name.time_stamp = "1970-01-01T00:00:00"
    f.header.file_name.preprocessor_version = "IfcOpenShell"
    f.header.file_name.originating_system = "IfcOpenShell"


def pass_if(condition: bool, *, errors_if_fail: int = 1) -> Result:
    return "pass" if condition else FailObj(expected_count=errors_if_fail)


def fail_if(condition: bool, *, errors_if_fail: int = 1) -> Result:
    return pass_if(not condition, errors_if_fail=errors_if_fail)


def parse_result(fixture_path: Path) -> Result:
    name = fixture_path.name
    if name.startswith("fail-"):
        expected_count = 1
        if match := re.search(r"^fail-expected-(\d+)", name):
            expected_count = int(match.group(1))
        return FailObj(expected_count=expected_count)
    if name.startswith("pass-"):
        return "pass"
    raise ValueError(f"Fixture filename must start with 'fail-' or 'pass-': {name}")


def write_fixture(file: ifcopenshell.file, source: str, result: Result, stem: str) -> None:
    content = file.to_string()
    content += f"/* IFC fixture is generated by {Path(source).name} */\n"
    match result:
        case FailObj(expected_count=expected_count):
            prefix = "fail" if expected_count == 1 else f"fail-expected-{expected_count}"
        case _:
            prefix = result
    Path(f"{prefix}-{stem}.ifc").write_text(content)


if __name__ == "__main__":
    directory = Path(__file__).parent

    for path in directory.glob("*.ifc"):
        path.unlink()

    for path in sorted(directory.glob("generate_*.py")):
        print(f"=== {path.name} ===")
        subprocess.run([sys.executable, str(path)], cwd=directory, check=True)
