import subprocess
import sys
from pathlib import Path
from typing import Literal, TypeAlias

import ifcopenshell

directory = Path(__file__).parent

Result: TypeAlias = Literal["fail", "pass"]


def normalize_header(f: ifcopenshell.file) -> None:
    f.header.file_name.time_stamp = "1970-01-01T00:00:00"
    f.header.file_name.preprocessor_version = "IfcOpenShell"
    f.header.file_name.originating_system = "IfcOpenShell"


def pass_if(condition: bool) -> Result:
    return "pass" if condition else "fail"


def fail_if(condition: bool) -> Result:
    return "fail" if condition else "pass"


def write_fixture(file: ifcopenshell.file, source: str, result: Result, path: str) -> None:
    content = file.to_string()
    content += f"/* IFC fixture is generated by {Path(source).name} */\n"
    Path(f"{result}-{path}.ifc").write_text(content)


if __name__ == "__main__":
    for path in directory.glob("*.ifc"):
        path.unlink()

    for path in sorted(directory.glob("generate_*.py")):
        print(f"=== {path.name} ===")
        subprocess.run([sys.executable, str(path)], cwd=directory, check=True)
