[build-system]
requires = ["setuptools>=77.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ifcpatch"
version = "0.0.0"
authors = [
  { name="Dion Moult", email="dion@thinkmoult.com" },
]
description = "Utility for applying modification recipes to IFC files"
readme = "README.md"
requires-python = ">=3.11"
license = "LGPL-3.0-or-later"
keywords = ["IFC", "BIM"]
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = ["ifcopenshell", "numpy"]

[project.scripts]
ifcpatch = "ifcpatch.__main__:main"

[project.optional-dependencies]
advanced = [
  "sqlite3",
  "mysql-connector-python",
]

[project.urls]
Homepage = "http://ifcopenshell.org"
Documentation = "https://docs.ifcopenshell.org"
Issues = "https://github.com/IfcOpenShell/IfcOpenShell/issues"

[tool.setuptools.packages.find]
include = ["ifcpatch*"]
exclude = ["test*"]

[tool.ruff]
extend = "../../pyproject.toml"
