#!/usr/bin/env python3
# This file was generated with the assistance of an AI coding tool.
"""Generate a typed .pyi stub for one IFC schema (issue #3306).

The stub declares one class per schema entity, with real attribute types and
schema inheritance, plus a ``file`` subclass whose ``by_type()`` overloads
return per-class typed lists. It is a purely static typing layer: the stub
module does not exist at runtime and runtime behavior is unchanged.

Schema data is introspected from the compiled schemas that ship with the
ifcopenshell wrapper (the same source ``file.by_type()`` uses at runtime),
so an installed/built ifcopenshell is required to run this script.

Known simplifications (documented, not silently wrong):
- LIST/SET/ARRAY/BAG all map to ``tuple[X, ...]`` (what the wrapper returns);
  aggregate bounds are not encoded in the type.
- EXPRESS LOGICAL maps to ``bool | Literal["UNKNOWN"]`` (runtime returns the
  string "UNKNOWN" for the unknown value).
- Derived attributes keep their supertype's declared type; WHERE rules and
  subtype constraints are not represented.
- ``entity_instance.__getattr__`` returns ``Any``, so misspelled attribute
  names still silently type as ``Any``; declared attributes get real types.
- ``file.schema`` and every entity's inherited ``.schema`` are narrowed to a
  ``Literal`` of this one schema, so a type checker can discriminate a
  ``Union[ifc2x3.file, ifc4.file, ifc4x3.file]`` on ``f.schema == "..."`` (or
  a per-instance ``Union`` on ``inst.schema == "..."``) with plain inference
  and get schema-specific attributes, no cast needed.

Usage:
    python generate_typed_stubs.py            # print this message
    python generate_typed_stubs.py IFC4       # write ifcopenshell/ifc4.pyi

Run black on the output afterwards (the repo formats .pyi files too).
"""

import argparse
import sys
from pathlib import Path

import ifcopenshell.ifcopenshell_wrapper as wrapper

PACKAGE_DIR = Path(__file__).parent.parent / "ifcopenshell"

HEADER = """\
# IfcOpenShell - IFC toolkit and geometry engine
# Copyright (C) 2026 IfcOpenShell contributors
#
# This file is part of IfcOpenShell.
#
# IfcOpenShell is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# IfcOpenShell is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with IfcOpenShell.  If not, see <http://www.gnu.org/licenses/>.

# This file was generated with the assistance of an AI coding tool.
# Generated by scripts/generate_typed_stubs.py for schema {schema}. Do not edit.
#
# Static typing layer only (https://github.com/IfcOpenShell/IfcOpenShell/issues/3306):
# this stub-only module cannot be imported at runtime. Use it for annotations,
# e.g. `if TYPE_CHECKING: from ifcopenshell import {module}` and
# `walls = cast("list[{module}.IfcWall]", model.by_type("IfcWall"))`, or cast a
# model to `{module}.file` to get typed `by_type("IfcWall")` results directly.

from typing import Literal, TypeAlias, TypeVar, Union, overload

import ifcopenshell
from ifcopenshell.entity_instance import entity_instance

_T = TypeVar("_T", bound=entity_instance)
"""

# How the wrapper converts EXPRESS simple types to Python values at runtime.
SIMPLE_TYPES = {
    "string": "str",
    "real": "float",
    "number": "float",
    "integer": "int",
    "boolean": "bool",
    "logical": 'Union[bool, Literal["UNKNOWN"]]',
    "binary": "str",
}


def type_expr(param_type: wrapper.parameter_type, quote: bool) -> str:
    """Map an EXPRESS attribute/defined type to a Python type expression."""
    aggregation = param_type.as_aggregation_type()
    if aggregation is not None:
        return f"tuple[{type_expr(aggregation.type_of_element(), quote)}, ...]"
    named = param_type.as_named_type()
    if named is not None:
        name = named.declared_type().name()
        return f'"{name}"' if quote else name
    simple = param_type.as_simple_type()
    assert simple is not None, f"unexpected parameter type: {param_type}"
    return SIMPLE_TYPES[str(simple.declared_type())]


def emit_aliases(schema: wrapper.schema_definition, lines: list[str]) -> None:
    # Alias values are resolved eagerly by type checkers even in stubs, so all
    # declaration references are quoted to make declaration order irrelevant.
    for decl in schema.declarations():
        enumeration = decl.as_enumeration_type()
        if enumeration is not None:
            items = ", ".join(f'"{item}"' for item in enumeration.enumeration_items())
            lines.append(f"{decl.name()}: TypeAlias = Literal[{items}]")
            continue
        select = decl.as_select_type()
        if select is not None:
            members = [f'"{d.name()}"' for d in select.select_list()]
            value = f"Union[{', '.join(members)}]" if len(members) > 1 else members[0]
            lines.append(f"{decl.name()}: TypeAlias = {value}")
            continue
        type_declaration = decl.as_type_declaration()
        if type_declaration is not None:
            lines.append(f"{decl.name()}: TypeAlias = {type_expr(type_declaration.declared_type(), quote=True)}")


def emit_entity(entity: wrapper.entity, lines: list[str], emitted: set[str], root_base: str) -> None:
    if entity.name() in emitted:
        return
    supertype = entity.supertype()
    if supertype is not None:
        emit_entity(supertype, lines, emitted, root_base)
    emitted.add(entity.name())

    base = supertype.name() if supertype is not None else root_base
    body: list[str] = []
    for attribute in entity.attributes():
        annotation = type_expr(attribute.type_of_attribute(), quote=False)
        if attribute.optional():
            annotation += " | None"
        body.append(f"    {attribute.name()}: {annotation}")
    # The wrapper only exposes inverse attributes including inherited ones,
    # so the supertype's are subtracted to redeclare only what is new here.
    inherited = {i.name() for i in supertype.all_inverse_attributes()} if supertype is not None else set()
    for inverse in entity.all_inverse_attributes():
        if inverse.name() not in inherited:
            body.append(f"    {inverse.name()}: tuple[{inverse.entity_reference().name()}, ...]")

    lines.append("")
    if body:
        lines.append(f"class {entity.name()}({base}):")
        lines.extend(body)
    else:
        lines.append(f"class {entity.name()}({base}): ...")


def emit_file_class(schema_name: str, entities: list[wrapper.entity], lines: list[str]) -> None:
    lines.append("")
    lines.append("class file(ifcopenshell.file):")
    lines.append(f'    schema: Literal["{schema_name}"]')
    lines.append("    @overload")
    lines.append("    def by_type(self, type: type[_T], include_subtypes: bool = True) -> list[_T]: ...")
    for entity in entities:
        name = entity.name()
        lines.append("    @overload")
        lines.append(
            f'    def by_type(self, type: Literal["{name}"], include_subtypes: bool = True) -> list[{name}]: ...'
        )
    lines.append("    @overload")
    lines.append("    def by_type(self, type: str, include_subtypes: bool = True) -> list[entity_instance]: ...")


def generate(schema_name: str) -> Path:
    schema = wrapper.schema_by_name(schema_name)
    module = schema.name().lower()
    lines = [HEADER.format(schema=schema.name(), module=module)]

    emit_aliases(schema, lines)

    # A synthetic root so every entity in this schema (not just `file`) carries
    # a schema-specific `Literal` for `.schema`, letting a type checker narrow
    # a cross-schema `Union[ifc4.X, ifc4x3.X]` instance on `inst.schema == "..."`
    # with plain inference, the same discriminated-union technique as `file`.
    root_base = "_RootEntity"
    lines.append("")
    lines.append(f"class {root_base}(entity_instance):")
    lines.append(f'    schema: Literal["{schema.name()}"]')

    entities = [d.as_entity() for d in schema.declarations() if d.as_entity() is not None]
    emitted: set[str] = set()
    for entity in entities:
        emit_entity(entity, lines, emitted, root_base)
    emit_file_class(schema.name(), entities, lines)

    output = PACKAGE_DIR / f"{module}.pyi"
    output.write_text("\n".join(lines) + "\n")
    return output


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("schema", nargs="?", help="schema name known to the wrapper, e.g. IFC4")
    args = parser.parse_args()

    if not args.schema:
        print(__doc__)
        return

    try:
        output = generate(args.schema)
    except RuntimeError as e:
        sys.exit(str(e))
    print(f"Wrote '{output}'.")


if __name__ == "__main__":
    main()
