from __future__ import annotations

from .binding_ir import BindingIR
from .c_handle_rendering import _handle_storage_type
from .debug import debug_log


def _render_internal_header(spec: BindingIR, header_name: str) -> str:
    """Render the private C++ header shared by generated and in-tree C++ code."""
    debug_log(
        "c_backend.render_internal_header.start",
        f"module={spec.module} handles={len(spec.handles)}",
    )
    handle_structs = []
    for handle in spec.handles.values():
        storage_type = _handle_storage_type(handle)
        if handle.ptr_type == "shared_ptr":
            handle_structs.append(
                f"struct {handle.c_type} {{\n    {storage_type} ptr;\n}};"
            )
        elif handle.ptr_type == "value":
            handle_structs.append(
                f"struct {handle.c_type} {{\n    {storage_type} value;\n}};"
            )
        else:
            handle_structs.append(
                f"struct {handle.c_type} {{\n    {storage_type} ptr;\n    bool owned;\n}};"
            )
    handle_structs_block = "\n\n".join(handle_structs)
    includes = "\n".join(
        f"#include {header}" if header.startswith("<") else f'#include "{header}"'
        for header in spec.public_headers
    )
    guard = f"{spec.c_prefix.upper()}_API_INTERNAL_HPP"
    helper_block = ""
    if "file" in spec.handles and "instance" in spec.handles:
        file_handle_type = spec.handles["file"].c_type
        instance_handle_type = spec.handles["instance"].c_type
        helper_block = f"""
// ------------------------------------------------------------------
// Handle wrap/unwrap helpers
// ------------------------------------------------------------------
//
// These thin inline accessors let handwritten C++ translation units convert
// between the opaque public handle types and the underlying C++ pointers
// without duplicating the struct layouts. They preserve the `owned` flag
// when wrapping so that callers can decide whether the returned handle
// should free its target when destroyed.

inline ifcopenshell::file* unwrap_file({file_handle_type}* h) {{
    return h ? h->ptr : nullptr;
}}

inline const ifcopenshell::file* unwrap_file(const {file_handle_type}* h) {{
    return h ? h->ptr : nullptr;
}}

inline express::base* unwrap_instance({instance_handle_type}* h) {{
    return h ? &h->value : nullptr;
}}

inline const express::base* unwrap_instance(const {instance_handle_type}* h) {{
    return h ? &h->value : nullptr;
}}

inline {instance_handle_type}* wrap_instance(const express::base& value) {{
    if (!value) return nullptr;
    return new {instance_handle_type}{{value}};
}}

inline {instance_handle_type}* wrap_instance(const express::base* value) {{
    return value ? wrap_instance(*value) : nullptr;
}}

inline {file_handle_type}* wrap_file(ifcopenshell::file* p, bool owned = true) {{
    if (!p) return nullptr;
    auto* h = new {file_handle_type};
    h->ptr = p;
    h->owned = owned;
    return h;
}}
"""
    rendered = f"""// Auto-generated by src/ifcwrap/binding_generator/generate.py.
// Do not edit by hand; regenerate via the binding generator.
//
// This header exposes the C++ definitions backing the opaque handle types
// declared in {header_name}. It is intended for INTERNAL use by C++ translation
// units that want to interoperate with the autogen C API natively. It is NOT a
// public/installed header.

#ifndef {guard}
#define {guard}

#include "{header_name}"

#include <memory>
#include <sstream>
#include <string>
#include <vector>

{includes}

{handle_structs_block}

namespace ifcopenshell {{
namespace capi {{

// Thread-local storage for the most recent error string. Populated by
// set_last_error() and read via the public {spec.c_prefix}_last_error_message().
extern thread_local std::string g_last_error;
extern thread_local int g_last_error_kind;
extern thread_local int g_last_error_code;

// Set the global error message that will be returned by
// {spec.c_prefix}_last_error_message(). Use this from external translation
// units (e.g. high-level handwritten functions) to participate in the same
// error reporting channel as the autogen API.
void set_last_error(const std::string& message);
void set_last_error(int kind, const std::string& message);
void set_last_error(int kind, int code, const std::string& message);
int last_error_kind();
void set_error_from_current_exception();

{helper_block}

}} // namespace capi
}} // namespace ifcopenshell

#endif // {guard}
"""
    debug_log(
        "c_backend.render_internal_header.done",
        f"module={spec.module} bytes={len(rendered)}",
    )
    return rendered
