FROM ifcopenshell-build-env:updated

# Update system
RUN dnf update -y

# Clean the caches
RUN dnf clean all && \
    rm -rf /var/cache/dnf

# Setup uv
COPY --from=ghcr.io/astral-sh/uv:0.11.27 /uv /uvx /bin/

# Install Python
RUN uv python install

CMD ["sleep", "infinity"]
