{% set name = "ifcopenshell" %}
{% set version = "0.7.0" %}
{% set occt_version = "7.6.2" %}
{% set cgal_cpp_version = "5.3" %}
{% set hdf5_version = "1.12.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ..

build:
  binary_relocation: false [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja >=1.10.2
    - cmake
    - swig >=4.0.2

  host:
    - python
    - occt >={{ occt_version }}
    - hdf5 >={{ hdf5_version }}
    - cgal-cpp >={{ cgal_cpp_version }}
    - nlohmann_json
    - libxml2

  run:
    - python
    - occt >={{ occt_version }}
    - cgal-cpp >={{ cgal_cpp_version }}
    - hdf5 >={{ hdf5_version }}
    - lark-parser
    - deepdiff
    - requests
    - nlohmann_json
    - isodate
    - numpy >=1.17

test:
  imports:
    - ifcopenshell
  requires:
    - pytest
    - pytest-cov
    - numpy
    - lxml
    - isodate
    - lark
    - networkx
    - xmlschema
  #source_files:
  #  - src/ifcopenshell-python/test/api
  #  - src/ifcopenshell-python/test/util
  #  - src/ifcopenshell-python/test/bootstrap.py
  #  - src/ifcopenshell-python/test/test_file.py
  #  - src/ifcopenshell-python/test/test_wall_opening.py
  #  - src/ifcopenshell-python/test/__init__.py
  #commands:
  #  #- pip install bcf-client
  #  - cd ../src/ifcopenshell-python/test && pytest -p no:pytest-blender

about:
  home: http://ifcopenshell.org
  license: LGPL-3.0-or-later
  license_file: COPYING
  summary: 'IfcOpenShell is a library to support the IFC file format'
  description: |
    IfcOpenShell is an open source (LGPL) software library for 
    working with the Industry Foundation Classes (IFC) file format.
  doc_url: http://ifcopenshell.org/
  dev_url: https://github.com/IfcOpenShell/IfcOpenShell
