# Bonsai - OpenBIM Blender Add-on
# Copyright (C) 2026
#
# This file is part of Bonsai.
#
# Bonsai is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bonsai is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bonsai.  If not, see <http://www.gnu.org/licenses/>.
#
# This file was generated with the assistance of an AI coding tool.

"""Pins the door-flip contract of ``bim.toggle_door_swing`` (#8399).

Three legs:

* ``is_external_door`` — the pure decision feeding the confirmation gate.
  External doors are factory-handed: the flipped door is a different product,
  so the swing-arc click must ask before applying.
* invoke wiring — external doors route through ``invoke_confirm``; internal
  doors flip straight away; Shift is captured before the dialog.
* OperationType sync — finishing a hand flip on an occurrence whose
  ``BBIM_Door`` pset lives on its IfcDoorType must update the type's
  ``OperationType`` too (the type's pset and mapped geometry are already
  regenerated by the edit, so a stale type attribute would contradict both).
"""

from types import SimpleNamespace
from unittest.mock import Mock, patch

import bpy
import ifcopenshell
import ifcopenshell.api.pset
import ifcopenshell.api.root
import ifcopenshell.api.type
import ifcopenshell.util.element
import pytest

import bonsai.core.geometry
import bonsai.core.root
import bonsai.tool as tool
from bonsai.bim.module.model.door import ToggleDoorSwing
from test.bim.bootstrap import NewFile

pytestmark = pytest.mark.model


class TestIsExternalDoor:
    """Truth table for the confirmation-gate decision, on plain IFC files."""

    def _door(self, is_external=None, pset_on_type=False):
        f = ifcopenshell.file(schema="IFC4")
        door = ifcopenshell.api.root.create_entity(f, ifc_class="IfcDoor")
        target = door
        if pset_on_type:
            target = ifcopenshell.api.root.create_entity(f, ifc_class="IfcDoorType")
            ifcopenshell.api.type.assign_type(f, related_objects=[door], relating_type=target)
        if is_external is not None:
            pset = ifcopenshell.api.pset.add_pset(f, product=target, name="Pset_DoorCommon")
            ifcopenshell.api.pset.edit_pset(f, pset=pset, properties={"IsExternal": is_external})
        return door

    def test_none_element_is_not_external(self):
        assert ToggleDoorSwing.is_external_door(None) is False

    def test_door_without_pset_is_not_external(self):
        assert ToggleDoorSwing.is_external_door(self._door()) is False

    def test_door_with_is_external_true_needs_confirm(self):
        assert ToggleDoorSwing.is_external_door(self._door(is_external=True)) is True

    def test_door_with_is_external_false_skips_confirm(self):
        assert ToggleDoorSwing.is_external_door(self._door(is_external=False)) is False

    def test_is_external_inherited_from_type_needs_confirm(self):
        assert ToggleDoorSwing.is_external_door(self._door(is_external=True, pset_on_type=True)) is True


class TestInvokeGate:
    """The invoke wiring: dialog only for external doors, Shift captured first."""

    def _invoke(self, *, element, shift=False):
        op = SimpleNamespace(
            skip_direction_change=False,
            is_external_door=ToggleDoorSwing.is_external_door,
            execute=Mock(return_value={"FINISHED"}),
        )
        context = Mock()
        event = Mock(shift=shift)
        with patch.object(tool.Blender, "get_active_object", return_value=Mock()), patch.object(
            tool.Ifc, "get_entity", return_value=element
        ):
            result = ToggleDoorSwing.invoke(op, context, event)
        return op, context, result

    def _external_door(self):
        f = ifcopenshell.file(schema="IFC4")
        door = ifcopenshell.api.root.create_entity(f, ifc_class="IfcDoor")
        pset = ifcopenshell.api.pset.add_pset(f, product=door, name="Pset_DoorCommon")
        ifcopenshell.api.pset.edit_pset(f, pset=pset, properties={"IsExternal": True})
        return door

    def test_external_door_routes_through_confirm_dialog(self):
        op, context, _result = self._invoke(element=self._external_door())
        context.window_manager.invoke_confirm.assert_called_once()
        op.execute.assert_not_called()

    def test_internal_door_flips_without_dialog(self):
        f = ifcopenshell.file(schema="IFC4")
        door = ifcopenshell.api.root.create_entity(f, ifc_class="IfcDoor")
        op, context, result = self._invoke(element=door)
        context.window_manager.invoke_confirm.assert_not_called()
        op.execute.assert_called_once()
        assert result == {"FINISHED"}

    def test_shift_recorded_before_dialog_so_confirm_keeps_mirror_mode(self):
        op, _context, _result = self._invoke(element=self._external_door(), shift=True)
        assert op.skip_direction_change is True


def _add_parametric_door_type():
    """Parametric IfcDoorType (BBIM_Door on the type) plus one occurrence."""
    mesh = bpy.data.meshes.new("DT")
    tobj = bpy.data.objects.new("DT", mesh)
    dtype = bonsai.core.root.assign_class(
        tool.Ifc, tool.Collector, tool.Root, obj=tobj, ifc_class="IfcDoorType", should_add_representation=False
    )
    bpy.ops.object.select_all(action="DESELECT")
    bpy.context.view_layer.objects.active = tobj
    tool.Blender.select_object(tobj)
    bpy.ops.bim.add_door()
    bpy.ops.bim.add_occurrence(relating_type_id=dtype.id())
    occurrence = tool.Ifc.get().by_type("IfcDoor")[0]
    obj = tool.Ifc.get_object(occurrence)
    tool.Blender.set_objects_selection(bpy.context, obj, (obj,))
    return dtype, occurrence, obj


def _flip_active_door():
    bpy.ops.bim.enable_editing_door()
    bpy.ops.bim.toggle_door_swing(flip_geometry=False)
    bpy.ops.bim.finish_editing_door()


class TestOperationTypeSync(NewFile):
    def test_flip_on_typed_occurrence_updates_type_operation_type(self):
        bpy.ops.bim.create_project()
        dtype, occurrence, _obj = _add_parametric_door_type()
        assert dtype.OperationType == "SINGLE_SWING_LEFT"

        _flip_active_door()

        assert occurrence.OperationType == "SINGLE_SWING_RIGHT"
        assert dtype.OperationType == "SINGLE_SWING_RIGHT"
        pset = ifcopenshell.util.element.get_pset(dtype, "BBIM_Door")
        import json

        assert json.loads(pset["Data"])["door_type"] == "SINGLE_SWING_RIGHT"

    def test_flip_on_untyped_door_updates_occurrence_only(self):
        bpy.ops.bim.create_project()
        bpy.ops.mesh.add_door()
        obj = bpy.context.view_layer.objects.active
        element = tool.Ifc.get_entity(obj)

        _flip_active_door()

        assert element.OperationType == "SINGLE_SWING_RIGHT"
        assert ifcopenshell.util.element.get_type(element) is None

    def test_flip_leaves_bare_type_without_bbim_door_pset_untouched(self):
        bpy.ops.bim.create_project()
        bpy.ops.mesh.add_door()
        obj = bpy.context.view_layer.objects.active
        element = tool.Ifc.get_entity(obj)
        f = tool.Ifc.get()
        bare_type = ifcopenshell.api.root.create_entity(f, ifc_class="IfcDoorType")
        bare_type.OperationType = "SINGLE_SWING_LEFT"
        ifcopenshell.api.type.assign_type(f, related_objects=[element], relating_type=bare_type)

        _flip_active_door()

        assert element.OperationType == "SINGLE_SWING_RIGHT"
        assert bare_type.OperationType == "SINGLE_SWING_LEFT"
