schema_version = "1.0.0"
id = "bonsai"
version = "0.0.0"
name = "Bonsai"
tagline = "A native Building Information Model authoring platform using IFC"
maintainer = "Dion Moult <dion@thinkmoult.com>"
type = "add-on"
website = "https://bonsaibim.org/"
tags = [
    "3D View",
    "Add Mesh",
    "Animation",
    "Camera",
    "Development",
    "Import-Export",
    "Lighting",
    "Material",
    "Modeling",
    "Mesh",
    "Node",
    "Object",
    "Pipeline",
    "Render",
    "Scene",
    "System",
    "User Interface",
    "UV"
]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
platforms = ["os-arch"]
permissions.network = "Augin / Cove.Tool integration for VR and environmental analysis"
permissions.files = "Load and save IFCs, IDS, BCF, etc from disk"
permissions.clipboard = "Copy and paste error logs"
