# Bonsai - OpenBIM Blender Add-on
# Copyright (C) 2026
#
# This file is part of Bonsai.
#
# Bonsai is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bonsai is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bonsai.  If not, see <http://www.gnu.org/licenses/>.
#
# This file was generated with the assistance of an AI coding tool.

import bpy
import ifcopenshell.api.root
import ifcopenshell.util.element

import bonsai.tool as tool
from test.bim.bootstrap import NewFile


class TestSyncReferencesAutoAnnotations(NewFile):
    def setup_elevation_drawing(self):
        bpy.ops.bim.create_project()
        tool.Project.save_test_project()
        ifc = tool.Ifc.get()
        bpy.ops.bim.load_drawings()
        tool.Drawing.get_document_props().target_view = "ELEVATION_VIEW"
        bpy.ops.bim.add_drawing()
        drawing = next(a for a in ifc.by_type("IfcAnnotation") if a.ObjectType == "DRAWING")
        bpy.ops.bim.activate_drawing(drawing=drawing.id())
        return drawing

    def add_manual_annotation(self):
        tool.Drawing.get_annotation_props().object_type = "SECTION_LEVEL"
        before = set(tool.Ifc.get().by_type("IfcAnnotation"))
        bpy.ops.bim.add_annotation()
        bpy.ops.object.mode_set(mode="OBJECT")
        (annotation,) = set(tool.Ifc.get().by_type("IfcAnnotation")) - before
        return annotation

    def get_annotations(self, object_type):
        return [a for a in tool.Ifc.get().by_type("IfcAnnotation") if a.ObjectType == object_type]

    def test_manual_annotation_survives_activating_the_drawing(self):
        drawing = self.setup_elevation_drawing()
        manual = self.add_manual_annotation()
        manual_guid = manual.GlobalId

        bpy.ops.bim.activate_drawing(drawing=drawing.id())

        assert tool.Ifc.get().by_guid(manual_guid)

    def test_generated_annotation_is_marked_and_removed_with_its_reference(self):
        drawing = self.setup_elevation_drawing()
        ifc = tool.Ifc.get()
        (generated,) = self.get_annotations("SECTION_LEVEL")
        manual = self.add_manual_annotation()
        assert ifcopenshell.util.element.get_pset(generated, "EPset_Annotation", "IsAutoGenerated") is True
        assert not ifcopenshell.util.element.get_pset(manual, "EPset_Annotation", "IsAutoGenerated")
        manual_guid = manual.GlobalId

        ifcopenshell.api.root.remove_product(ifc, product=ifc.by_type("IfcBuildingStorey")[0])
        bpy.ops.bim.activate_drawing(drawing=drawing.id())

        assert [a.GlobalId for a in self.get_annotations("SECTION_LEVEL")] == [manual_guid]
