/********************************************************************************
 *                                                                              *
 * This file is part of IfcOpenShell.                                           *
 *                                                                              *
 * IfcOpenShell is free software: you can redistribute it and/or modify         *
 * it under the terms of the Lesser GNU General Public License as published by  *
 * the Free Software Foundation, either version 3.0 of the License, or          *
 * (at your option) any later version.                                          *
 *                                                                              *
 * IfcOpenShell is distributed in the hope that it will be useful,              *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of               *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the                 *
 * Lesser GNU General Public License for more details.                          *
 *                                                                              *
 * You should have received a copy of the Lesser GNU General Public License     *
 * along with this program. If not, see <http://www.gnu.org/licenses/>.         *
 *                                                                              *
 ********************************************************************************/


#include "WavefrontObjSerializer.h"

#include "../ifcgeom/IfcGeomRenderStyles.h"

#include "../ifcparse/utils.h"

#include <boost/lexical_cast.hpp>
#include <iomanip>
#include <map>
#include <tuple>

WaveFrontOBJSerializer::WaveFrontOBJSerializer(const stream_or_filename& obj_filename, const stream_or_filename& mtl_filename, const ifcopenshell::geometry::Settings& geometry_settings, const ifcopenshell::geometry::SerializerSettings& settings, Logger* logger)
	: WriteOnlyGeometrySerializer(geometry_settings, settings, logger_or_root(logger))
	, obj_stream(obj_filename)
	, mtl_stream(mtl_filename)
	, vcount_total(1)
	, ncount_total(1)
	, uvcount_total(1)
{
	obj_stream.stream << std::setprecision(settings.get<ifcopenshell::geometry::settings::FloatingPointDigits>().get());
	mtl_stream.stream << std::setprecision(settings.get<ifcopenshell::geometry::settings::FloatingPointDigits>().get());
}

bool WaveFrontOBJSerializer::ready() {
	return obj_stream.is_ready() && mtl_stream.is_ready();
}

void WaveFrontOBJSerializer::writeHeader() {
	obj_stream.stream << "# File generated by IfcOpenShell " << IFCOPENSHELL_VERSION << "\n";
#ifdef WIN32
	const char dir_separator = '\\';
#else
	const char dir_separator = '/';
#endif
	if (mtl_stream.filename()) {
		std::string mtl_basename = *mtl_stream.filename();
		std::string::size_type slash = mtl_basename.find_last_of(dir_separator);
		if (slash != std::string::npos) {
			mtl_basename = mtl_basename.substr(slash + 1);
		}
		obj_stream.stream << "mtllib " << mtl_basename << "\n";
	}
	mtl_stream.stream << "# File generated by IfcOpenShell " << IFCOPENSHELL_VERSION << "\n";
}

void WaveFrontOBJSerializer::writeMaterial(const ifcopenshell::geometry::taxonomy::style::ptr styleptr)
{
	auto& style = *styleptr;
	std::string material_name = style.name;
    IfcUtil::sanitate_material_name(material_name);
    mtl_stream.stream << "newmtl " << material_name << "\n";

	{
        auto& diffuse = style.get_color().ccomponents();
		mtl_stream.stream << "Kd " << diffuse(0) << " " << diffuse(1) << " " << diffuse(2) << "\n";
	}
	if (style.specular) {
		auto& specular = style.specular.ccomponents();
		mtl_stream.stream << "Ks " << specular(0) << " " << specular(1) << " " << specular(2) << "\n";
	}
	if (style.specularity == style.specularity) {
		mtl_stream.stream << "Ns " << style.specularity << "\n";
	}
	if (style.transparency == style.transparency) {
		const double transparency = 1.0 - style.transparency;
		if (transparency < 1) {
			mtl_stream.stream << "d "  << transparency << "\n";
		}
	}
}

void WaveFrontOBJSerializer::write(const IfcGeom::TriangulationElement* o)
{
    obj_stream.stream << "g " << object_id(o) << "\n";
	obj_stream.stream << "s 1" << "\n";
	const bool isyup = settings().get<ifcopenshell::geometry::settings::UseYUp>().get();

    const IfcGeom::Representation::Triangulation& mesh = o->geometry();

    const bool has_uvs = !mesh.uvs().empty();
	const bool has_normals = !mesh.normals().empty();

	// When vertices are not welded (the common case when normals are requested), mesh.verts()
	// and mesh.normals() hold one entry per triangle corner, so identical position/normal values
	// are repeated many times. OBJ's "f v/vt/vn" syntax indexes positions, texture coordinates
	// and normals independently, so positions and normals are deduplicated here on their own
	// terms and referenced through separate index streams below, rather than being forced to
	// share a single combined index as before.
	std::vector<double> dedup_verts;
	std::vector<double> dedup_normals;
	std::vector<int> pos_index;
	std::vector<int> norm_index;

	if (has_normals) {
		typedef std::tuple<double, double, double> Triplet;
		std::map<Triplet, int> pos_map;
		std::map<Triplet, int> norm_map;
		const std::vector<double>& verts = mesh.verts();
		const std::vector<double>& normals = mesh.normals();
		const size_t n = verts.size() / 3;
		pos_index.reserve(n);
		norm_index.reserve(n);
		for (size_t i = 0; i < n; ++i) {
			const Triplet pk(verts[i * 3], verts[i * 3 + 1], verts[i * 3 + 2]);
			auto pit = pos_map.find(pk);
			if (pit == pos_map.end()) {
				const int pidx = (int)(dedup_verts.size() / 3);
				pos_map.emplace(pk, pidx);
				dedup_verts.push_back(std::get<0>(pk));
				dedup_verts.push_back(std::get<1>(pk));
				dedup_verts.push_back(std::get<2>(pk));
				pos_index.push_back(pidx);
			} else {
				pos_index.push_back(pit->second);
			}

			const Triplet nk(normals[i * 3], normals[i * 3 + 1], normals[i * 3 + 2]);
			auto nit = norm_map.find(nk);
			if (nit == norm_map.end()) {
				const int nidx = (int)(dedup_normals.size() / 3);
				norm_map.emplace(nk, nidx);
				dedup_normals.push_back(std::get<0>(nk));
				dedup_normals.push_back(std::get<1>(nk));
				dedup_normals.push_back(std::get<2>(nk));
				norm_index.push_back(nidx);
			} else {
				norm_index.push_back(nit->second);
			}
		}
	}

	const std::vector<double>& verts_to_write = has_normals ? dedup_verts : mesh.verts();
	size_t vcount = verts_to_write.size() / 3;
    size_t ncount = dedup_normals.size() / 3;
    size_t uvcount = mesh.uvs().size() / 2;

	for (auto it = verts_to_write.begin(); it != verts_to_write.end();) {
        const double x = *(it++);
        const double y = *(it++);
        const double z = *(it++);

		if (isyup) {
			obj_stream.stream << "v " << x << " " << z << " " << -y << "\n";
		} else {
			obj_stream.stream << "v " << x << " " << y << " " << z << "\n";
		}
	}

	for (auto it = dedup_normals.begin(); it != dedup_normals.end();) {
        const double x = *(it++);
        const double y = *(it++);
        const double z = *(it++);
		obj_stream.stream << "vn " << x << " " << y << " " << z << "\n";
	}

	for (auto it = mesh.uvs().begin(); it != mesh.uvs().end();) {
        const double u = *it++;
        const double v = *it++;
        obj_stream.stream << "vt " << u << " " << v << "\n";
    }

	int previous_material_id = -2;
	std::vector<int>::const_iterator material_it = mesh.material_ids().begin();
	for ( std::vector<int>::const_iterator it = mesh.faces().begin(); it != mesh.faces().end(); ) {
		
		const int material_id = *(material_it++);
		if (material_id != previous_material_id) {
			const ifcopenshell::geometry::taxonomy::style::ptr material = mesh.materials()[material_id];
			std::string material_name = material->name;
            IfcUtil::sanitate_material_name(material_name);
			obj_stream.stream << "usemtl " << material_name << "\n";
			if (materials.find(material_name) == materials.end()) {
				writeMaterial(material);
				materials.insert(material_name);
			}
			previous_material_id = material_id;
		}

		const int idx1 = *(it++);
		const int idx2 = *(it++);
		const int idx3 = *(it++);

		const int v1 = (has_normals ? pos_index[idx1] : idx1) + (int)vcount_total;
		const int v2 = (has_normals ? pos_index[idx2] : idx2) + (int)vcount_total;
		const int v3 = (has_normals ? pos_index[idx3] : idx3) + (int)vcount_total;

		const int n1 = has_normals ? norm_index[idx1] + (int)ncount_total : 0;
        const int n2 = has_normals ? norm_index[idx2] + (int)ncount_total : 0;
        const int n3 = has_normals ? norm_index[idx3] + (int)ncount_total : 0;

		// UV indices are left as the original per-corner indices (not deduplicated): a UV is a
		// function of both position and normal (box projection), so it cannot be safely indexed
		// through either the position or the normal dedup map alone.
		const int t1 = idx1 + (int)uvcount_total;
		const int t2 = idx2 + (int)uvcount_total;
		const int t3 = idx3 + (int)uvcount_total;

        if (has_normals && has_uvs) {
			obj_stream.stream << "f " << v1 << "/" << t1 << "/" << n1 << " "
				<< v2 << "/" << t2 << "/" << n2 << " "
				<< v3 << "/" << t3 << "/" << n3 << "\n";
		} else if (has_normals) {
            obj_stream.stream << "f " << v1 << "//" << n1 << " "
				<< v2 << "//" << n2 << " "
				<< v3 << "//" << n3 << "\n";
		} else {
			obj_stream.stream << "f " << v1 << " " << v2 << " " << v3 << "\n";
		}
	}

	std::set<int> faces_set (mesh.faces().begin(), mesh.faces().end());
	const std::vector<int>& edges = mesh.edges();

	for ( std::vector<int>::const_iterator it = edges.begin(); it != edges.end(); ) {
		const int i1 = *(it++);
		const int i2 = *(it++);

		if (faces_set.find(i1) != faces_set.end() || faces_set.find(i2) != faces_set.end()) {
			continue;
		}

		const int material_id = *(material_it++);

		if (material_id != previous_material_id) {
			const ifcopenshell::geometry::taxonomy::style::ptr material = mesh.materials()[material_id];
			std::string material_name = material->name;
            IfcUtil::sanitate_material_name(material_name);
			obj_stream.stream << "usemtl " << material_name << "\n";
			if (materials.find(material_name) == materials.end()) {
				writeMaterial(material);
				materials.insert(material_name);
			}
			previous_material_id = material_id;
		}

		const int v1 = (has_normals ? pos_index[i1] : i1) + (int)vcount_total;
		const int v2 = (has_normals ? pos_index[i2] : i2) + (int)vcount_total;

		obj_stream.stream << "l " << v1 << " " << v2 << "\n";
	}

	vcount_total += vcount;
    ncount_total += ncount;
    uvcount_total += uvcount;
}
