package:
  name: ifcopenshell
  # Placeholder, replaced by build_pyodide.sh with the actual version from VERSION file.
  version: 9.9.9

source:
  # meta.yaml is placed as `packages/ifcopenshell/meta.yaml`.
  path: ../../IfcOpenShell

build:
  script: |
    BUILD_CFG=Release python nix/build-all.py -v --wasm

about:
  home: http://ifcopenshell.org
  license: LGPL-3.0-or-later
  summary: |
    IfcOpenShell is an open source (LGPL) software library for 
    working with the Industry Foundation Classes (IFC) file format.
