# Bonsai - OpenBIM Blender Add-on
# Copyright (C) 2025, 2026 Michael Yoder <myoder@desertspringscivil.com>
#
# This file is part of Bonsai.
#
# Bonsai is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bonsai is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bonsai.  If not, see <http://www.gnu.org/licenses/>.


"""Core alignment business logic - Orchestration only, NO bpy imports.

This module contains alignment-related business logic and workflow
orchestration. All calculations, algorithms, and IFC operations are
in the tool layer. Functions receive tool classes as parameters
following Bonsai's dependency injection pattern.

NOTE: Math, calculations, algorithms, and IFC API calls belong in
tool/alignment.py. This module only handles:
- Business rules and validation
- Workflow orchestration (calling tool methods in sequence)
- Decision-making about what should happen
"""

from __future__ import annotations
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    import ifcopenshell
    from .. import tool


# =============================================================================
# Alignment Creation
# =============================================================================


def create_alignment(
    ifc_tool: "type[tool.Ifc]",
    alignment_tool: "type[tool.Alignment]",
    name: str,
    start_station: float = 0.0,
) -> "ifcopenshell.entity_instance":
    """Create a new alignment with full IFC structure.

    Business rules:
    1. An IFC file must be loaded
    2. Name must not be empty
    3. Delegates to tool layer for IFC creation and Blender hierarchy

    Args:
        ifc_tool: The IFC tool class
        alignment_tool: The Alignment tool class
        name: The alignment name
        start_station: Starting station value

    Returns:
        The created IfcAlignment entity

    Raises:
        ValueError: If no IFC file is loaded or name is empty
    """
    if ifc_tool.get() is None:
        raise ValueError("No IFC file loaded")

    if not name or not name.strip():
        raise ValueError("Alignment name cannot be empty")

    return alignment_tool.create_alignment(name.strip(), start_station)


def import_alignment_csv(
    ifc_tool: "type[tool.Ifc]",
    alignment_tool: "type[tool.Alignment]",
    filepath: str,
):
    """Import alignment(s) from a CSV file and build their viewport objects.

    Business rules:
    1. An IFC file must be loaded
    2. The CSV may carry one horizontal row plus any number of vertical rows;
       extra verticals arrive as aggregated child alignments and each child
       gets its own viewport hierarchy
    3. Referents generated by the import are materialized as empties

    Args:
        ifc_tool: The IFC tool class
        alignment_tool: The Alignment tool class
        filepath: Path to the CSV file

    Returns:
        The imported (parent) IfcAlignment entity

    Raises:
        ValueError: If no IFC file is loaded
    """
    ifc_file = ifc_tool.get()
    if ifc_file is None:
        raise ValueError("No IFC file loaded")

    alignment = alignment_tool.create_alignment_from_csv(filepath)

    alignment_tool.create_hierarchy_for_alignment(alignment)
    parent_obj = ifc_tool.get_object(alignment)
    for child in alignment_tool.get_child_alignments(alignment):
        # Child alignments (IFC CT 4.1.4.4.1.2) are vertical-only wrappers.
        # We skip creating a Blender empty for them so they don't clutter the
        # scene collection.  Their vertical layouts go under the parent object.
        alignment_tool.create_child_vertical_hierarchy(child, parent_obj)
    alignment_tool.create_objects_for_referents(alignment)

    return alignment
