#
# Generate the WASM plugin manifest from entries passed via IFCOPENSHELL_WASM_PLUGIN_ENTRIES.
# Plugin artifacts are copied to IFCOPENSHELL_WASM_PLUGINS_DIR by per-target POST_BUILD
# commands; this script only writes the JSON manifest.

if(NOT DEFINED IFCOPENSHELL_WASM_PLUGINS_JSON)
    message(FATAL_ERROR "IFCOPENSHELL_WASM_PLUGINS_JSON is required")
endif()
if(NOT DEFINED IFCOPENSHELL_WASM_PLUGIN_ENTRIES)
    set(IFCOPENSHELL_WASM_PLUGIN_ENTRIES "")
endif()

string(REPLACE "@" ";" plugin_entry_list "${IFCOPENSHELL_WASM_PLUGIN_ENTRIES}")

set(manifest_content "{\n")
set(first_kind TRUE)
foreach(kind IN ITEMS schema kernel tree mapping document geometry_serializer)
    set(kind_entries "")
    foreach(entry IN LISTS plugin_entry_list)
        if(NOT entry MATCHES "^[^|]+\\|[^|]+\\|")
            continue()
        endif()
        string(REPLACE "|" ";" entry_parts "${entry}")
        list(GET entry_parts 0 entry_kind)
        if(NOT entry_kind STREQUAL kind)
            continue()
        endif()
        list(APPEND kind_entries "${entry}")
    endforeach()
    if(NOT kind_entries)
        continue()
    endif()
    if(NOT first_kind)
        string(APPEND manifest_content ",\n")
    endif()
    set(first_kind FALSE)
    string(APPEND manifest_content "  \"${kind}\": {\n")
    set(first_id TRUE)
    foreach(entry IN LISTS kind_entries)
        string(REPLACE "|" ";" entry_parts "${entry}")
        list(GET entry_parts 1 plugin_id)
        list(GET entry_parts 2 output_name)
        set(depends_json "")
        list(LENGTH entry_parts entry_parts_length)
        if(entry_parts_length GREATER 3)
            list(GET entry_parts 3 depends_csv)
            if(NOT depends_csv STREQUAL "")
                string(REPLACE "," ";" depends_list "${depends_csv}")
                set(first_dependency TRUE)
                foreach(dep IN LISTS depends_list)
                    if(dep STREQUAL "")
                        continue()
                    endif()
                    if(first_dependency)
                        set(first_dependency FALSE)
                    else()
                        string(APPEND depends_json ", ")
                    endif()
                    string(APPEND depends_json "\"${dep}\"")
                endforeach()
            endif()
        endif()
        if(NOT first_id)
            string(APPEND manifest_content ",\n")
        endif()
        set(first_id FALSE)
        string(APPEND manifest_content "    \"${plugin_id}\": {\"wasm\": \"plugins/${output_name}.wasm\"")
        if(NOT depends_json STREQUAL "")
            string(APPEND manifest_content ", \"depends\": [${depends_json}]")
        endif()
        string(APPEND manifest_content "}")
    endforeach()
    string(APPEND manifest_content "\n  }")
endforeach()
if(NOT first_kind)
    string(APPEND manifest_content "\n")
endif()
string(APPEND manifest_content "}\n")
file(WRITE "${IFCOPENSHELL_WASM_PLUGINS_JSON}" "${manifest_content}")
