[build-system]
requires = [
    "setuptools>=61",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "bcf-client"
# author = "IfcOpenShell"
description = "BCF-XML file handler."
readme = "README.md"
requires-python = ">=3.10"
keywords = ["IFC", "BCF", "BIM"]
dependencies = [
    "xsdata>=24.4",
    "numpy",
    "ifcopenshell",
    "requests",
]
version = "0.0.0"
classifiers = [
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering",
    "Topic :: Utilities",
]

[project.urls]
Source = "https://github.com/IfcOpenShell/IfcOpenShell"
Issues = "https://github.com/IfcOpenShell/IfcOpenShell/issues"

[tool.coverage.paths]
source = ["src"]

[tool.coverage.run]
branch = true
source = ["bcf"]
omit = ["*/model/*"]

[tool.coverage.report]
show_missing = true
fail_under = 65
exclude_lines = [
    "pragma: no cover",
    "if TYPE_CHECKING",
    "if __name__ == .__main__.:",
    "Protocol",
]

[tool.tox]
legacy_tox_ini = """
[tox]
env_list = py3{10,11}
skip_missing_interpreters = true

[testenv]
deps =
    pytest
    pytest-cov
    coverage
commands = pytest --cov --cov-report=term tests
"""

[tool.ruff]
extend = "../../pyproject.toml"
lint.extend-select = [
  "unused-import",
]
