# IfcOpenShell - IFC toolkit and geometry engine
# Copyright (C) 2021 Thomas Krijnen <thomas@aecgeeks.com>
#
# This file is part of IfcOpenShell.
#
# IfcOpenShell is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# IfcOpenShell is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with IfcOpenShell.  If not, see <http://www.gnu.org/licenses/>.
"""Typing tests for ifcopenshell.

This file should produce no warnings from type checker (currently pyright).
Those tests are not automatically checked and just there to make sure overloads are making sense.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Union, cast

from typing_extensions import TypeIs, assert_type

import ifcopenshell

if TYPE_CHECKING:
    # Stub-only modules generated by scripts/generate_typed_stubs.py (issue #3306).
    from ifcopenshell import ifc4, ifc4x3


def ifcopenshell_open_test(str_: str, bool_: bool):
    ifc_file = ifcopenshell.open(str_)
    assert_type(ifc_file, Union[ifcopenshell.file, ifcopenshell.sqlite])

    ifc_file = ifcopenshell.open(str_, should_stream=bool_)
    assert_type(ifc_file, Union[ifcopenshell.file, ifcopenshell.sqlite, ifcopenshell.stream])

    ifc_file = ifcopenshell.open(str_, should_stream=True)
    assert_type(ifc_file, ifcopenshell.stream)

    ifc_file = ifcopenshell.open(str_, readonly=True)


def get_inverse_test(ifc_file: ifcopenshell.file, inst: ifcopenshell.entity_instance, bool_: bool):
    # Default: allow_duplicate=False, with_attribute_indices=False
    result = ifc_file.get_inverse(inst)
    assert_type(result, set[ifcopenshell.entity_instance])

    # Explicit allow_duplicate=False
    result = ifc_file.get_inverse(inst, allow_duplicate=False)
    assert_type(result, set[ifcopenshell.entity_instance])

    # allow_duplicate=True without indices
    result = ifc_file.get_inverse(inst, allow_duplicate=True)
    assert_type(result, list[ifcopenshell.entity_instance])

    # allow_duplicate=True with indices
    result = ifc_file.get_inverse(inst, allow_duplicate=True, with_attribute_indices=True)
    assert_type(result, list[tuple[ifcopenshell.entity_instance, int]])

    # Dynamic bool values (falls back to generic overload)
    result = ifc_file.get_inverse(inst, allow_duplicate=bool_)
    assert_type(result, list[ifcopenshell.entity_instance] | set[ifcopenshell.entity_instance])


def ifc4_typed_by_type_test(f: ifc4.file, str_: str):
    # `ifc4.file` is a static-only typed facade over `ifcopenshell.file`:
    # annotate or cast a model to it, then string `by_type()` calls get typed results.
    walls = f.by_type("IfcWallStandardCase")
    assert_type(walls, list[ifc4.IfcWallStandardCase])

    # Dynamic strings fall back to the plain `entity_instance` overload.
    assert_type(f.by_type(str_), list[ifcopenshell.entity_instance])

    # Passing the class object also types (static only: at runtime `by_type()`
    # takes a string and the stub-only classes do not exist as objects).
    assert_type(f.by_type(ifc4.IfcWall), list[ifc4.IfcWall])


def ifc4_attribute_types_test(wall: ifc4.IfcWallStandardCase):
    # Attribute types are inherited through the schema hierarchy (IfcRoot etc.).
    assert_type(wall.GlobalId, str)
    assert_type(wall.Name, Union[str, None])
    assert_type(wall.OwnerHistory, Union[ifc4.IfcOwnerHistory, None])
    assert_type(wall.PredefinedType, Union[ifc4.IfcWallTypeEnum, None])
    # Inverse attributes are tuples of the referencing relationship entities.
    assert_type(wall.HasOpenings, tuple[ifc4.IfcRelVoidsElement, ...])


def ifc4_optional_chain_test(v: ifc4.IfcWallStandardCase):
    # The z() example from issue #3306: chaining through an optional relation
    # type checks after narrowing (and is an error without it).
    if v.OwnerHistory:
        assert_type(v.OwnerHistory.CreationDate, int)


def multi_schema_file_narrowing_test(f: Union[ifc4.file, ifc4x3.file]):
    # aothms's PR #8698 comment, snippet 2: narrowing a schema-agnostic file
    # handle via `f.schema` before calling `by_type()`. `file.schema` is
    # generated as a per-schema `Literal` (not the base `IFC_SCHEMA` union),
    # so this is plain discriminated-union narrowing: no cast needed.
    if f.schema == "IFC4X3":
        assert_type(f, ifc4x3.file)
        for inst in f.by_type("IfcCartesianPointList3D"):
            assert_type(inst, ifc4x3.IfcCartesianPointList3D)
            assert_type(inst.TagList, Union[tuple[ifc4x3.IfcLabel, ...], None])
    else:
        assert_type(f, ifc4.file)
        for inst in f.by_type("IfcCartesianPointList3D"):
            assert_type(inst, ifc4.IfcCartesianPointList3D)


def _is_ifc4x3_point_list(
    inst: Union[ifc4.IfcCartesianPointList3D, ifc4x3.IfcCartesianPointList3D],
) -> TypeIs[ifc4x3.IfcCartesianPointList3D]:
    return inst.file.schema == "IFC4X3"


def multi_schema_instance_narrowing_test(f: ifcopenshell.file):
    # aothms's snippet 1: by_type() called on an un-narrowed handle, then
    # narrowing per-instance via `inst.file.schema`. Two gaps versus snippet 2:
    # the schema-agnostic `by_type()` has no typed overload (needs a cast to
    # get a cross-schema Union at all), and plain equality narrowing does not
    # propagate from `inst.file.schema` back to `inst` (they're different
    # expressions), so narrowing `inst` itself needs a user-defined `TypeIs`
    # predicate per entity/schema pair rather than inference alone.
    insts = cast(
        "list[Union[ifc4.IfcCartesianPointList3D, ifc4x3.IfcCartesianPointList3D]]",
        f.by_type("IfcCartesianPointList3D"),
    )
    for inst in insts:
        if _is_ifc4x3_point_list(inst):
            assert_type(inst, ifc4x3.IfcCartesianPointList3D)
            assert_type(inst.TagList, Union[tuple[ifc4x3.IfcLabel, ...], None])
