name: Build IfcOpenShell Linux

on:
  workflow_dispatch:

jobs:
  build_ifcopenshell:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Build Repository
        uses: actions/checkout@v7
        with:
          repository: IfcOpenShell/build-outputs
          ref: main
          path: build-outputs-init
          token: ${{ secrets.BUILD_REPO_TOKEN }}

      - name: Create Build Repository Branch
        run: |
          cd build-outputs-init
          git checkout -b rockylinux9-x64-shared
          mkdir -p Linux/x86_64/install
          touch Linux/x86_64/install/.gitkeep
          git add Linux/x86_64/install/.gitkeep
          git commit -m "Add install dir skeleton [skip ci]"
          git push origin rockylinux9-x64-shared
