name: Build IfcOpenShell WASM / Pyodide

on:
  workflow_dispatch:

jobs:
  build_ifcopenshell:
    runs-on: ubuntu-22.04

    steps:
      - name: Set up uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0

      - name: Install Python
        # Installs latest Python version so it's preferred by uv over system Python.
        run: uv python install

      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          submodules: recursive
          path: IfcOpenShell

      - name: Checkout Build Repository
        uses: actions/checkout@v7
        with:
          repository: IfcOpenShell/build-outputs
          path: ifcopenshell_build
          ref: wasm
          lfs: true
          token: ${{ secrets.BUILD_REPO_TOKEN }}

      - name: Unpack Dependencies
        run: |
          cd ifcopenshell_build
          uv run ../IfcOpenShell/nix/cache_dependencies.py unpack

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2.23
        with:
          key: ubuntu-22.04-${{ runner.arch }}

      - name: Build
        run: |
          ./IfcOpenShell/pyodide/build_pyodide.sh
          FILE=`echo dist/ifcopenshell-*.whl`
          NEW_FILE=`echo $FILE | sed "s/-/+${GITHUB_SHA:0:7}-/2"`
          mv $FILE $NEW_FILE

      - name: Upload Build Logs
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: build-logs-pyodide
          path: |
            ifcopenshell_build/*/*/logs/*.log
          retention-days: 30

      - name: Pack Dependencies
        run: |
          cd ifcopenshell_build
          uv run ../IfcOpenShell/nix/cache_dependencies.py pack

      - name: Commit and Push Changes to Build Repository
        run: |
          cd ifcopenshell_build
          git config user.name "IfcOpenBot"
          git config user.email "ifcopenbot@ifcopenshell.org"
          git add */*/install/cache-*.tar.gz
          git commit -m "Update build artifacts [skip ci]" || echo "No changes to commit"
          git push || echo "Push failed"

      - name: Order wheel shared objects
        run: |
          uv run ./IfcOpenShell/pyodide/order_pyodide_wheel_shared_objects.py dist/ifcopenshell-*.whl

      - name: Split packages
        run: |
          VERSION=v`cat ./IfcOpenShell/VERSION`
          mkdir -p dist-modular
          uv run ./IfcOpenShell/pyodide/split_pyodide_ifcopenshell_wheel.py dist/ifcopenshell-*.whl ./dist-modular
          cd dist-modular
          zip -r -qq ifcopenshell-modular-${VERSION}-${GITHUB_SHA:0:7}-pyodide.zip *.whl

      - name: Run wheel tests
        run: |
          # venv set up in build_pyodide.sh.
          source .venv/bin/activate
          ln -s "$PWD/dist" IfcOpenShell/dist
          ln -s "$PWD/dist-modular" IfcOpenShell/dist-modular
          cd IfcOpenShell/pyodide
          ./run_pytest.py setup
          ./run_pytest.py run

      - name: Setup tmate session
        if: failure()
        uses: mxschmitt/action-tmate@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_UPLOAD_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_UPLOAD_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload .zip archives to S3
        run: |
          aws s3 cp dist s3://ifcopenshell-builds/ --recursive --exclude "*" --include "*.whl"
          aws s3 cp dist-modular s3://ifcopenshell-builds/ --recursive --exclude "*" --include "*.zip"
