name: Build IfcOpenShell

on:
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workflow:
          - 'Build IfcOpenShell Linux'
          - 'Build IfcOpenShell Linux ARM'
          - 'Build IfcOpenShell macOS'
          - 'Build IfcOpenShell WASM'
          - 'Build IfcOpenShell Windows'
    steps:
      - name: Trigger binary build workflows
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: ${{ matrix.workflow }}
