name: Build IfcOpenShell WASM / Pyodide

on:
  workflow_dispatch:

jobs:
  build_ifcopenshell:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          path: IfcOpenShell

      - name: Checkout Pyodide
        uses: actions/checkout@v3
        with:
          submodules: recursive
          repository: pyodide/pyodide
          ref: '0.28.0a3'
          token: ${{ secrets.BUILD_REPO_TOKEN }}
          path: pyodide

      - name: Build
        run: |
          VERSION=`cat IfcOpenShell/VERSION`
          sed -i s/0.8.0/$VERSION/g IfcOpenShell/pyodide/meta.yaml
          sed -i s/--tty// pyodide/run_docker
          pyodide/run_docker IfcOpenShell/pyodide/build_pyodide.sh
          FILE=`echo dist/ifcopenshell-*.whl`
          NEW_FILE=`echo $FILE | sed "s/$VERSION/$VERSION+${GITHUB_SHA:0:7}/"`
          mv $FILE $NEW_FILE

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_UPLOAD_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_UPLOAD_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload .zip archives to S3
        run: |
          aws s3 cp dist s3://ifcopenshell-builds/ --recursive --exclude "*" --include "*.whl"
