name: ci-ifcopenshell-conda-daily-cleaner

on:
  workflow_dispatch:
  schedule:
  #         ┌───────────── minute (0 - 59)
  #         │  ┌───────────── hour (0 - 23)
  #         │  │ ┌───────────── day of the month (1 - 31)
  #         │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
  #         │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
  #         *  * * * *
  - cron: "00 23 * * *" # 11min before utc midnight every day

env:
  ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
  NUM_SUPPORTED_VERSIONS: 5

jobs:
  activate:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    if: |
      github.repository == 'IfcOpenShell/IfcOpenShell'
    steps:
      - uses: actions/checkout@v7

      - uses: mamba-org/setup-micromamba@v3 # https://github.com/mamba-org/setup-micromamba
        with:
          environment-name: test-env
          create-args: >-
            python=3.11
            anaconda-client=1.12.3

      - name: Run conda cleaner
        run: python conda/clean-old-versions.py
