name: ci-ifctester-org

on:
  workflow_dispatch:

jobs:
  publish_websites:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - working-directory: ./src/ifctester
        env:
          GH_APIKEY: ${{ secrets.GH_APIKEY }}
          OSC_APIKEY: ${{ secrets.OSC_APIKEY }}
        run: |
          sudo apt update && sudo apt install -y nodejs
          git config --global user.name 'IfcOpenBot'
          git config --global user.email 'IfcOpenBot@users.noreply.github.com'
          git clone https://${{ secrets.GH_APIKEY }}@github.com/IfcOpenShell/ifctester_org_static_html
          make webapp-build
          git -C ifctester_org_static_html add webapp/dist/*
          git -C ifctester_org_static_html commit --allow-empty -m "$(git log --oneline -1)"
          git -C ifctester_org_static_html push
