name: ci-ifcedit-pypi

on:
  workflow_dispatch:

jobs:
  activate:
    runs-on: ubuntu-latest
    if: |
      github.repository == 'IfcOpenShell/IfcOpenShell'
    steps:
    - name: Set env
      run: echo ok go

  build:
    needs: activate
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: Compile
        run: |
          pip install build
          cd src/ifcedit &&
          make dist IS_STABLE=TRUE
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: src/ifcedit/dist
