name: ci_nix

on:
  push:
    paths:
      - 'src/**'
      - 'test/**'
      - 'conda/**'
      - 'cmake/**'
      - '.github/workflows/ci-nix-build.yml'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
            submodules: recursive
      - name: Install C++ dependencies
        run: |
          sudo apt update
          sudo apt-get install --no-install-recommends \
          git gcc g++ autoconf bison make cmake libfreetype6-dev mesa-common-dev libffi-dev libfontconfig1-dev patch

      - name: Build ifcopenshell
        run: |
          cd nix && python3 build-all.py
