name: Restart failed daily conda builds

on:
  workflow_run:
    workflows: [ ci-ifcopenshell-conda-daily ]
    types:
      - completed
  push: # Remove this before merging
    branches:
    - add-conda-daily-restart-workflow

env:
  REPO_OWNER: IfcOpenShell
  MY_WORKFLOW: ci-ifcopenshell-conda-daily

jobs:
  restart-failed-runs:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Check for failed runs
        id: check-failed-runs
        run: |
          python check_repo_ci_jobs.py
