name: Restart failed daily conda builds

on:
  workflow_run:
    workflows: [ ci-ifcopenshell-conda-daily ]
    types:
      - completed

env:
  REPO_OWNER: IfcOpenShell/IfcOpenShell
  MY_WORKFLOW: ci-ifcopenshell-conda-daily

jobs:
  restart-failed-runs:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Use python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Check for failed runs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORKFLOW_RUN_ID: ${{ github.event.workflow_run.id }}
        run: |
          python check_repo_ci_jobs.py
        working-directory: .github/workflows
