name: ci

on:
  push:
    paths:
      - 'src/ifcblender/**'
      - 'src/ifcconvert/**'
      - 'src/ifcgeom/**'
      - 'src/ifcgeom_schema_agnostic/**'
      - 'src/ifcgeomserver/**'
      - 'src/ifcjni/**'
      - 'src/ifcmax/**'
      - 'src/ifcopenshell-python/**'
      - '!src/ifcopenshell-python/docs/**'
      - 'src/ifcparse/**'
      - 'src/ifcwrap/**'
      - 'src/qtviewer/**'
      - 'src/svgfill/**'
      - 'src/serializers/**'
      - 'conda/**'
      - 'cmake/**'
      - '.github/workflows/ci.yml'
  pull_request:

jobs:
  activate:
    runs-on: ubuntu-22.04
    if: |
      github.repository == 'IfcOpenShell/IfcOpenShell' &&
      !contains(github.event.head_commit.message, 'skip ci')
    steps:
      - run: echo ok go

  compile-and-test:
    runs-on: ubuntu-22.04
    needs: activate
    env:
      # Colored output for cmake.
      CLICOLOR_FORCE: "1"
      CMAKE_COLOR_DIAGNOSTICS: "ON"
    steps:
      - uses: actions/checkout@v6
        with:
            submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install xmlschema xsdata numpy lxml pytest isodate lark networkx tabulate python-dateutil shapely
          pip install src/bcf --no-deps
          pip install pytest-xdist==3.8.0 conan
      - name: Setup Conan Client
        uses: conan-io/setup-conan@v1
        with:
          version: 2.24.0
          config_urls: |
            .conan2/
          cache_packages: true
          profile_detect: false
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2.22
        with:
          key: ubuntu-22.04-${{ runner.arch }}
      - name: Install C++ dependencies
        run: |
          #TODO: use an optimized docker image with dependencies preinstalled 
          sudo apt -y remove swig cmake
          # Use lock files to speed up dependency resolution and ensure reproducible builds.
          # In case of dependency update, execute following command locally without --lockfile=.conan2/conan.lock to update .conan2/conan.lock and commit it.
          conan install . --lockfile=.conan2/conan.lock --lockfile-partial --lockfile-out=.conan2/conan.lock -pr:h=.conan2/profiles/linux_host -pr:b=.conan2/profiles/linux_host --build=missing
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install xmlschema xsdata numpy lxml pytest isodate lark networkx tabulate python-dateutil shapely
          pip install src/bcf --no-deps
          pip install pytest-xdist==3.8.0

      # TODO: Use https://github.com/assimp/assimp/tree/master instead of this lib not maintened since 2017.
      # OpenCOLLADA is ancient, but we still have it in the main build.
      # So adding it to CI to catch any breakages.
      - name: build OpenCOLLADA
        run: |
          git clone https://github.com/KhronosGroup/OpenCOLLADA
          cd OpenCOLLADA
          git checkout v1.6.68
          patch -p1 --batch --forward -i ../nix/patches/opencollada/pr622_and_disable_subdirs.patch
          patch -p1 --batch --forward -i ../nix/patches/opencollada/allow_static_libraries_config_on_unix.patch
          mkdir build && cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_FLAGS_INIT="-fPIC"
          sudo make -j$(nproc) install

      - name: Build ifcopenshell
        run: |
          echo $Python3_ROOT_DIR
          echo ${{ env.pythonLocation }}
          # conan build . -pr:h=.conan2/profiles/linux_host -pr:b=.conan2/profiles/linux_host

          cmake --preset conan-release
          cmake --build --preset conan-release
          cmake --install build/Release/ --prefix build/Release/install/

          conan export-pkg . -pr:h=.conan2/profiles/linux_host -pr:b=.conan2/profiles/linux_host

      # - name: Run IfcConvert on Sample files
      #   run: |
          # (find test/input src/bonsai/test/files -name '*.ifc' | while read i; do \
          #   echo $i | tee -a log; \
          #   timeout 1m "./build/Debug/ifcconvert/IfcConvert" -yv "$i" "$i.obj" --validate >> log 2>&1; \
          #   echo $i $? >> statuses; \
          # done) || true
      #     echo Failed
      #     grep -v 0$ statuses
      #     grep -v 0$ statuses | wc -l
      #     echo Succeeded
      #     grep 0$ statuses
      #     grep 0$ statuses | wc -l

      - name: Run IfcConvert on Sample file
        run: |
          ./build/Release/ifcconvert/IfcConvert test/input/acad2010_walls.ifc test/input/acad2010_walls.obj

      - name: Build standalone examples to test cmake package
        run: |
          conan test src/examples ifcopenshell/${cat VERSION} -pr:h=.conan2/profiles/linux_host -pr:b=.conan2/profiles/linux_host

      - name: Test ifcopenshell-python
        run: |
          export PYTHONPATH=$PWD/build/Release/install/lib/python/dist-packages/:$PYTHONPATH
          cd test
          python tests.py
          cd ../src/ifcopenshell-python
          mv ifcopenshell ifcopenshell-local # Force testing on installed module
          pip install -e ../ifcpatch --no-deps # Needed for sql.py tests.
          ERROR=0
          make test-parallel || ERROR=1
          cd ../bcf && make test || ERROR=1
          pip install requests
          cd ../bsdd && make test || ERROR=1
          pip install deepdiff
          cd ../ifcdiff && make test || ERROR=1
          cd ../ifcpatch && make test || ERROR=1
          pip install -e ../ifctester --no-deps
          cd ../ifctester && make test || ERROR=1
          make build-ids-docs || ERROR=1
          # Run mathutils related tests at the end to ensure no other code is relying on mathutils.
          cd ../ifcopenshell-python
          pip install mathutils
          make test-mathutils || ERROR=1
          if [ $ERROR -ne 0 ]; then
            echo "One or more tests failed";
            exit 1;
          fi
