name: Publish IfcOpenShell Conda Cleaner

on:
  workflow_dispatch:
  schedule:
  #         ┌───────────── minute (0 - 59)
  #         │  ┌───────────── hour (0 - 23)
  #         │  │ ┌───────────── day of the month (1 - 31)
  #         │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
  #         │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
  #         *  * * * *
  - cron: "00 23 * * *" # 11min before utc midnight every day

env:
  ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
  NUM_SUPPORTED_VERSIONS: 5

jobs:
  activate:
    runs-on: ubuntu-latest
    if: |
      github.repository == 'IfcOpenShell/IfcOpenShell'
    steps:
      - uses: actions/checkout@v7

      - name: Set up uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0

      - name: Run conda cleaner
        run: uv run --script conda/clean-old-versions.py
